// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Jayden T",
            "email": "support@jaydent.uk"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/timetable/version/{name}": {
            "get": {
                "description": "Returns the JSON timetable and its version ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timetable"
                ],
                "summary": "Takes a timetable name and returns the version ID",
                "operationId": "getVersionIDByName",
                "parameters": [
                    {
                        "type": "string",
                        "format": "json",
                        "description": "The name of the timetable you want (including .json)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the latest version ID",
                        "schema": {
                            "$ref": "#/definitions/api.GetVersionIDResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid timetable name",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/timetable/{name}": {
            "get": {
                "description": "Returns the JSON timetable and its version ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timetable"
                ],
                "summary": "Takes a timetable name and returns the latest JSON timetable data with its corresponding version ID",
                "operationId": "getTimetableByName",
                "parameters": [
                    {
                        "type": "string",
                        "format": "json",
                        "description": "The name of the timetable you want (including .json)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the latest timetable with version ID",
                        "schema": {
                            "$ref": "#/definitions/api.GetTimetableResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid timetable name",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.GetTimetableResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "versionID": {
                    "type": "string"
                }
            }
        },
        "api.GetVersionIDResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "transitIOMAPI",
	Description:      "This is an API for the transitIOM application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
